spring:
  jpa:
    show-sql:  true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  r2dbc:
    url: r2dbc:pool:mysql://127.0.0.1:3306/practice
    username: root
    password: root
  application:
    name: STATE
  config:
    import: configserver:http://localhost:8086
  webflux:
    base-path: /state
server:
  servlet:
    context-path-country: /country/
  port: 8088

management:
  zipkin:
    tracing:
      endpoint: http://localhost:8080/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
logging:
  level:
    root: info
    web: debug
    reactor:
      netty:
        http:
          client: DEBUG
